services:
  mongodb:
    image: mongo
    container_name: mongodb-ncloud-api
    ports:
      - "27017:27017"
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
  mongo-express:
    image: mongo-express
    container_name: mongo-express-ncloud-api
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
      - ME_CONFIG_MONGODB_SERVER=mongodb
  meilisearch:
      image: "getmeili/meilisearch"
      restart: unless-stopped
      ports:
        - "127.0.0.1:7700:7700"
      volumes:
        - /var/local/meilisearch:/data.ms
      env_file:
        - /var/local/meilisearch/meilisearch.env

volumes:
  data: { }

networks:
  default:
    name: mongodb_network